"""Shared non-financial business limits."""

MIN_TENANT_CONCURRENCY = 1
DEFAULT_TENANT_CONCURRENCY = 20
MAX_TENANT_CONCURRENCY = 30

MIN_WORKER_CONCURRENCY = 1
MAX_WORKER_CONCURRENCY = 100

MIN_BENCHMARK_TASKS = 1
MAX_BENCHMARK_TASKS = 100
